### ISSUE TITLE
Add a config option to filter certain workers

### ISSUE THREAD

**Issue by jfelchner** [lintci/sidekiq-skylight#2]
There are a lot of workers that we have which we don't care about getting metrics on.  A lot of them run every second or every 5 seconds which makes our number of requests end up being outrageous.  It'd be great to have an option to look at the worker name and not send to sidekiq if it was in a list of workers that we set in a configuration option.

**Comment by jfelchner** [comment]
@blatyo any chance you could do a release? :grin:

**Comment by blatyo** [comment]
Already is released. v0.1.0

**Comment by jfelchner** [comment]
:+1: thanks!
