### ISSUE TITLE
Renamespace?

### ISSUE THREAD

**Issue by mperham** [lintci/sidekiq-skylight#8]
When you create a gem foo-bar, your Ruby module is FooBar.  My gem is named sidekiq and my module is Sidekiq.  Your gem is sidekiq-skylight so your module is SidekiqSkylight, not Sidekiq::Skylight, which is injecting code into my module.

**Comment by blatyo** [comment]
I was following the convention of other gems, where dashes denote an extension to another library and are namespaced underneath it. If the intention were to call it `SidekiqSkylight`, the gem and project would be called `sidekiq_skylight` instead. You can see some examples here:

https://github.com/brynary/rack-test
https://github.com/sinatra/rack-protection

Others:
https://rubygems.org/search?utf8=%E2%9C%93&query=rack-

Is this causing an issue? `Skylight` seems unlikely as something you would use in `Sidekiq`. So, unless there's a compelling reason, like a conflict, I'd rather follow the convention.

**Comment by mperham** [comment]
I don't necessarily think those rack extensions are named correctly either, unless they are officially part of the Rack project.

It's not causing any known issues right now; this is more of an attempt to educate others and avoid future collisions.  Sidekiq::Cron is an example where I had to research and take care with my naming because Sidekiq Enterprise implements a similar feature.  Generally: don't put stuff into modules you don't own unless you are explicitly overriding something.

**Comment by blatyo** [comment]
This gem is deprecated
